replicaCount: 1

image:
  repository: ghcr.io/dev-alex-ops/backend-app
  pullPolicy: IfNotPresent
  tag: local

imagePullSecrets:
  - name: ghcr-secret

service:
  type: ClusterIP
  port: 3000

fullnameOverride: "backend"