replicaCount: 1

image:
  repository: ghcr.io/dev-alex-ops/frontend-app
  pullPolicy: IfNotPresent
  tag: local

imagePullSecrets:
  - name: ghcr-secret

service:
  type: ClusterIP
  port: 80

fullnameOverride: "frontend"